# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
# Create random tensor
x_rand = torch.rand(7, 7)
x_rand

tensor([[0.6526, 0.4771, 0.1654, 0.2876, 0.1003, 0.6573, 0.6806],
        [0.0705, 0.5964, 0.8470, 0.9278, 0.3608, 0.6968, 0.7964],
        [0.9739, 0.9959, 0.0638, 0.8995, 0.6263, 0.2387, 0.8961],
        [0.1866, 0.8334, 0.8319, 0.6197, 0.3112, 0.0079, 0.5798],
        [0.9693, 0.4233, 0.7721, 0.2309, 0.7636, 0.0070, 0.8867],
        [0.7664, 0.3575, 0.7299, 0.0401, 0.5027, 0.2754, 0.9336],
        [0.4427, 0.9916, 0.3770, 0.4251, 0.8736, 0.2175, 0.9864]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
x2_rand = torch.rand(1, 7)

# Perform matrix multiplication, x2.T da 1x7 a 7x1 -> 7x7 @ 7x1 -> 7x1
x = x_rand @ x2_rand.T
x


tensor([[1.8459],
        [2.9555],
        [3.3008],
        [2.5049],
        [2.6673],
        [2.2192],
        [2.9282]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
x1_rand = torch.rand(7, 7)
x2_rand = torch.rand(1, 7)


# Matrix multiply tensors
x = x1_rand @ x2_rand.T
x


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
seed_value = 1234
if torch.cuda.is_available():
    torch.cuda.manual_seed(seed_value)
else:
    print("CUDA is not available on this system.")



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# 1. Set the random seed
torch.manual_seed(1234)

# 2. Check for access to GPU and set the device
if torch.cuda.is_available():
    device = "cuda"
    print(f"Device: {device}")
else:
    device = "cpu"
    print(f"CUDA not available. Using device: {device}")
    print("Note: The tensors will be created on the CPU, and the 'device' output will show 'cpu'.")

# 3. Create two random tensors on the determined device
# Use .to(device) to ensure the tensor is created directly on the GPU if available
tensor_A = torch.rand(2, 3, device=device)
tensor_B = torch.rand(2, 3, device=device)

# Output the result
print(f"({tensor_A},\n {tensor_B})")

Device: cuda
(tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0'))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor = tensor_A @ tensor_B.T
(tensor, tensor.size())

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = tensor.max()
print(max)

# Find min
min = tensor.min()
print(min)

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
id_max = torch.argmax(tensor)
print(id_max)

# Find arg min
id_min = torch.argmin(tensor)
print(id_min)

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
"""
A dimension with a size of 1 (like the first three dimensions in our (1, 1, 1, 10) tensor) is called a singleton dimension.
Purpose:
- Singleton dimensions are often introduced when you Add a batch dimension:
  For example, converting a (3, 224, 224) image to a (1, 3, 224, 224) tensor for a neural network.
- Perform specific operations: Like taking the mean over a single dimension while keeping that dimension in the output (using keepdim=True).
- Need a specific rank/number of dimensions: To match an input requirement for another function.

Effect: They don't change the total number of elements in the tensor (it's still $1 \times 1 \times 1 \times 10 = 10$ elements), but they do change the tensor's rank (the number of dimensions).
"""

# 1. Set the seed
torch.manual_seed(7)

# 2. Create the first tensor
tensor_4d = torch.rand(1, 1, 1, 10)

# 3. Create the second tensor by removing singleton dimensions
tensor_1d = tensor_4d.squeeze() # squeeze() returns a tensor with all the dimensions of size 1 removed.

# 4. Print out tensors and their shapes
print(tensor_4d, tensor_4d.shape)
print(tensor_1d, tensor_1d.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
